name: CI

on: [push, pull_request]

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: snakemake
      uses: snakemake/snakemake-github-action@v1.17.0
      with:
        directory: test
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs --cores 1 --conda-cleanup-pkgs cache"
